# Cloudinary Plugin Konfiguration
[[plugins]]
  package = "netlify-plugin-cloudinary"

  [plugins.inputs]
  cloudName = "dwazywc11"
  deliveryType = "fetch"
  imagesPath = "/images"

# Netlify Prerender Plugin (für Google Bot etc.)
[[plugins]]
  package = "@netlify/plugin-prerender-spa"

# ChatBees AI Chatbot Plugin (trainiert auf Website-Inhalt, Update bei jedem Deploy)
[[plugins]]
  package = "netlify-plugin-chatbees"

# CSS Redirects
[[redirects]]
  from = "/css/*"
  to = "/css/:splat"
  status = 200
  force = true

# JavaScript Redirects
[[redirects]]
  from = "/js/*"
  to = "/js/:splat"
  status = 200
  force = true

# Images Redirects (Cloudinary nutzt das!)
[[redirects]]
  from = "/images/*"
  to = "/images/:splat"
  status = 200
  force = true

# Robots.txt
[[redirects]]
  from = "/robots.txt"
  to = "/robots.txt"
  status = 200
  force = true

# Sitemap
[[redirects]]
  from = "/sitemap.xml"
  to = "/sitemap.xml"
  status = 200
  force = true

# Catch-all für SPA (Single Page Application)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200